/home/miguel/snap/code/188/.local/share/pypoetry/venv/bin/python3: error while loading shared libraries: /home/miguel/snap/code/188/.local/share/pypoetry/venv/bin/../lib/libpython3.9.so.1.0: cannot open shared object file: No such file or directory

Traceback:

  File "<stdin>", line 937, in main
  File "<stdin>", line 576, in run
